export const tokenList = {
  "name": "PawSwap Default List",
  "timestamp": "2022-08-12T09:56:23Z",
  "version": {
    "major": 2,
    "minor": 1,
    "patch": 0
  },
  "tags": {},
  "logoURI": "https://exchange.pancakeswap.finance/images/pancakeswap.png",
  "keywords": ["pawswap", "default"],
  "tokens": [
    {
      "name": "Pawthereum",
      "symbol": "PAWTH",
      "address": "0x409e215738E31d8aB252016369c2dd9c2008Fee0",
      "chainId": 56,
      "decimals": 9,
      "logoURI": "https://assets.coingecko.com/coins/images/19275/large/pawth.png?1635127429",
      "typicalBuyTax": 8,
      "typicalSellTax": 8,
      "color": "#ff65b3",
      "description": "Pawthereum is a decentralized, charity cryptocurrency that gives back to animal shelters and advocates for the well-being of animals in need!",
      "isFeatured": true,
      "isPawthereum": true,
    },
    {
      "name": "Pawthereum",
      "symbol": "PAWTH",
      "address": "0x47aA79E41B12d239F8c1B7d8Dd33be9DF1802687",
      "chainId": 97,
      "decimals": 9,
      "logoURI": "https://assets.coingecko.com/coins/images/19275/large/pawth.png?1635127429",
      "typicalBuyTax": 8,
      "typicalSellTax": 8,
      "color": "#ff65b3",
      "description": "Pawthereum is a decentralized, charity cryptocurrency that gives back to animal shelters and advocates for the well-being of animals in need!",
      "isFeatured": true,
      "isPawthereum": true,
    },
    {
      "name": "Pawthereum",
      "symbol": "PAWTH",
      "address": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      "chainId": 1337,
      "decimals": 9,
      "logoURI": "https://assets.coingecko.com/coins/images/19275/large/pawth.png?1635127429",
      "typicalBuyTax": 8,
      "typicalSellTax": 8,
      "color": "#ff65b3",
      "description": "Pawthereum is a decentralized, charity cryptocurrency that gives back to animal shelters and advocates for the well-being of animals in need!",
      "isFeatured": true,
      "isPawthereum": true,
    },
    {
      "name": "Pawthereum",
      "symbol": "PAWTH",
      "address": "0xAEcc217a749c2405b5ebC9857a16d58Bdc1c367F",
      "chainId": 1,
      "decimals": 9,
      "logoURI": "https://assets.coingecko.com/coins/images/19275/large/pawth.png?1635127429",
      "typicalBuyTax": 2,
      "typicalSellTax": 2,
      "color": "#ff65b3",
      "description": "Pawthereum is a decentralized, charity cryptocurrency that gives back to animal shelters and advocates for the well-being of animals in need!",
      "isFeatured": true,
      "isPawthereum": true,
    },
    {
      "name": "BNB",
      "symbol": "BNB",
      "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
      "chainId": 1337,
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1644979850",
      "typicalBuyTax": 0,
      "typicalSellTax": 0,
      "color": "#F0BA03",
      "isNative": true,
      "isFeatured": true,
    },
    {
      "name": "BNB",
      "symbol": "BNB",
      "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
      "chainId": 97,
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1644979850",
      "typicalBuyTax": 0,
      "typicalSellTax": 0,
      "color": "#F0BA03",
      "isNative": true,
      "isFeatured": true,
    },
    {
      "name": "BNB",
      "symbol": "BNB",
      "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1644979850",
      "typicalBuyTax": 0,
      "typicalSellTax": 0,
      "color": "#F0BA03",
      "isNative": true,
      "isFeatured": true,
    },
    {
      "name": "Ethereum",
      "symbol": "ETH",
      "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
      "chainId": 1,
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/279/large/ethereum.png?1595348880",
      "typicalBuyTax": 0,
      "typicalSellTax": 0,
      "color": "#F0BA03",
      "isNative": true,
      "isFeatured": true,
    },
    //{
    //   "name": "Wrapped BNB",
    //   "symbol": "WBNB",
    //   "address": "0xae13d989dac2f0debff460ac112a837c89baa7cd",
    //   "chainId": 97,
    //   "decimals": 18,
    //   "logoURI": "https://cdn.icon-icons.com/icons2/3006/PNG/512/bnb_cryptocurrencies_icon_188408.png",
    //   "typicalBuyTax": 0,
    //   "typicalSellTax": 0,
    //   "color": "#F4BB0B",
    // },
    // {
    //   "name": "Kodi Coin",
    //   "symbol": "KODI",
    //   "address": "0x71a3406E8A04ec52b7f7aCcE94C93f7a48FBF2C9",
    //   "chainId": 97,
    //   "decimals": 18,
    //   "logoURI": "https://bafybeievtapjdh32pqp3kljnhhymzf6fc2kxkqsajsujac34j5wto3aisy.ipfs.infura-ipfs.io",
    //   "dex": "pancakeswap",
    //   "typicalBuyTax": 11,
    //   "typicalSellTax": 12,
    //   "color": "#8751D8"
    //   "description": "KODI is more than just a new project, it will provide immediate utility through the implementation of our marketing agency. Starting with our 24/7 Radio show, the Kodi team will be bringing you everything from crypto podcasts, music, and much more.",
    // },
    {
      "name": "SafeMoon",
      "symbol": "SFM",
      "address": "0x8a791620dd6260079bf849dc5567adc3f2fdc318",
      "chainId": 1337,
      "decimals": 9,
      "logoURI": "https://assets.coingecko.com/coins/images/21863/small/photo_2021-12-22_14.43.36.jpeg?1640155440",
      "dex": "pancakeswap",
      "typicalBuyTax": 10,
      "typicalSellTax": 10,
      "color": "#008A81",
      "description": "A human-focused technology and innovation business expanding blockchain technologies for a brighter tomorrow.",
      "isFeatured": true
    },
    {
      "name": "SafeMoon",
      "symbol": "SFM",
      "address": "0x44255F8De687371B5f7F8c9398A300e5a7628895",
      "chainId": 97,
      "decimals": 9,
      "logoURI": "https://assets.coingecko.com/coins/images/21863/small/photo_2021-12-22_14.43.36.jpeg?1640155440",
      "dex": "pancakeswap",
      "typicalBuyTax": 10,
      "typicalSellTax": 10,
      "color": "#008A81",
      "description": "A human-focused technology and innovation business expanding blockchain technologies for a brighter tomorrow.",
      "isFeatured": true
    },
    {
      "name": "GlowV2",
      "symbol": "GlowV2",
      "address": "0x05De1dbFCdc876F790371508b97C337640Dcd6a9",
      "chainId": 56,
      "decimals": 9,
      "logoURI": "https://assets.coingecko.com/coins/images/23301/large/17513.png?1643668784",
      "dex": "pancakeswap",
      "color": "#C90D0C",
      "description": "We present to you a token focused on giving back through a lottery for our holders, charitable donations, education to the masses, and empowering others to succeed and do good in the world while also being transparent in how we operate.",
      "isFeatured": true
    },
}
